/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ClearInv_text_h_
#define _ClearInv_text_h_
//---------------------------------------------------------------------------------
extern const unsigned char ClearInv_text[];
extern const int ClearInv_text_size;
//---------------------------------------------------------------------------------
#endif //_ClearInv_text_h_
//---------------------------------------------------------------------------------
